services:
  db:
    image: postgres:16-alpine
    container_name: medcontrol_db
    restart: always
    environment:
      POSTGRES_DB: medcontrol
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d medcontrol"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
